# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Jia-Ming Lu
tagline:          'Personal Page'
description:      'Personal page.'
url:              http://jaimeyzzz.github.io/
baseurl:          /

author:
  name:           'Jia-Ming Lu'
  url:            https://twitter.com/jaimeyzzz

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jaimeyzzz/jaimeyzzz.github.io
